web_site:
  - alias: alias_foo 
    user:
      id: id_foo
      pw: pw_foo
    blocked_author_memo_pattern: "foo pattern"
    # TODO(@pastry-personal5): To be deprecated. It's to use `blocked_author_memo_pattern` only.
    blocked_author_name:
      - foo
      - bar
      - baz
  - alias: alias_bar
    user:
      id: id_bar
      pw: pw_bar
    blocked_author_memo_pattern: "bar pattern"
    # TODO(@pastry-personal5): To be deprecated. It's to use `blocked_author_memo_pattern` only.
    blocked_author_name:
      - foobar
      - barbaz
      - bazfoo
